micronaut:
  application:
    name: estudosMicronaut
  server:
    port: 8081
netty:
  default:
    allocator:
      max-order: 3

twitter:
  apiKey: "5bXJquDNV0hKipR5m2vQbpjiv"
  apiKeySecret: "opG5q4btLXuodyUMpTzwH8c4rQiGa403ZpLI47NI0vZU8q43PP"
  accessTokenSecret: "WE7V0nr5iRCPThXQO5lAIVMXzH4Qp1hGC7OVNuoa6tUw4"
  bearerToken: "AAAAAAAAAAAAAAAAAAAAACrLjgEAAAAA4kZZWVbCn%2FpM8Hd%2BYKwP1qY9UZg%3DKa0W5j2OUL5lM50nDc5300r04SJ2u5PBRSJDTvGvuUs5cvOFgr"

nlu:
  url: "https://api.us-south.natural-language-understanding.watson.cloud.ibm.com/instances/b8e74164-9a33-4b9d-a46c-6ee96ec3c399"
  path: "/v1/analyze?version=2019-07-12"
  apiKey: "g6tmNPu2pJ8GcwhP5rdU9sgn-8nkS6tbZmWXpsftqM7A"
  version: "2019-07-12"

